### ISSUE TITLE
Error during deployment via circleci

### ISSUE THREAD

**Issue by phahulin** [poanetwork/poa-explorer-infra#30]
When deploying via circleCI I got the following error on `AfterInstall` step:
```
Error Code: ScriptFailed
Script Name: bin/deployment/build
Message: Script at specified location: bin/deployment/build run as user ec2-user failed with exit code 1
Log Tail[stdout]  idna 5.1.1
[stdout]  jason 1.0.0
[stdout]  jsx 2.8.3
[stdout]  junit_formatter 2.1.0
[stdout]  math 0.3.0
[stdout]  meck 0.8.9
[stdout]  metrics 1.0.1
[stdout]  mime 1.2.0
[stdout]  mimerl 1.0.2
[stdout]  mochiweb 2.15.0
[stdout]  mock 0.3.1
[stdout]  mox 0.3.2
[stdout]  parallel_stream 1.0.6
[stdout]  parse_trans 3.2.0
[stdout]  phoenix 1.3.0
[stdout]  phoenix_ecto 3.3.0
[stdout]  phoenix_html 2.10.5
[stdout]  phoenix_live_reload 1.1.3
[stdout]  phoenix_pubsub 1.0.2
[stdout]  plug 1.4.4
[stdout]  poison 3.1.0
[stdout]  poolboy 1.5.1
[stdout]  postgrex 0.13.5
[stdout]  qrcode 0.1.1
[stdout]  ranch 1.3.2
[stdout]  scrivener 2.5.0
[stdout]  scrivener_ecto 1.3.0
[stdout]  scrivener_html 1.7.1
[stdout]  sobelow 0.7.0
[stdout]  ssl_verify_fun 1.1.1
[stdout]  timex 3.1.25 RETIRED!
[stdout]  (invalid) Incorrect Elixir version requirement
[stdout]  timex_ecto 3.2.1
[stdout]  tzdata 0.5.16
[stdout]  unicode_util_compat 0.3.1
[stdout]  wallaby 0.20.0
[stderr]** (File.Error) could not make directory (with -p) "/opt/app/_build/prod/lib/parse_trans": no such file or directory
[stderr]    (elixir) lib/file.ex:271: File.mkdir_p!/1
[stderr]    (mix) lib/mix/tasks/deps.compile.ex:190: Mix.Tasks.Deps.Compile.do_rebar3/2
[stderr]    (mix) lib/mix/tasks/deps.compile.ex:85: anonymous fn/4 in Mix.Tasks.Deps.Compile.compile/2
[stderr]    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
[stderr]    (mix) lib/mix/tasks/deps.compile.ex:65: Mix.Tasks.Deps.Compile.compile/2
[stderr]    (mix) lib/mix/tasks/deps.loadpaths.ex:90: Mix.Tasks.Deps.Loadpaths.deps_check/2
[stderr]    (mix) lib/mix/tasks/deps.loadpaths.ex:27: Mix.Tasks.Deps.Loadpaths.run/1
[stderr]    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
```

**Comment by acravenho** [comment]
I experienced this same error after building explorer before deploying to AWS. 

I solved it by deleting the `_build`, `deps`, and `apps/explorer_web/assets/node_modules` folders and then using mix phx.digest to help locate assets once explorer was deployed on AWS. Something should be added to the build script to help this situation.
